dist: trusty
sudo: required
language: node_js
node_js:
  - '10'
cache:
  npm: true
  directories:
  - ~/.cache
  - '$HOME/.sonar/cache'
before_install:
  - npm install -g --silent @angular/cli
install:
  - npm ci
addons:
  chrome: stable
  sonarcloud:
    organization: "piemasters-github"
    token:
      secure: $SONARCLOUD_TOKEN
jdk:
  - oraclejdk8
script:
  - ng build --prod --aot
  - ng test --browsers=ChromeHeadless --watch=false
  - npm run e2e:ci
  - sonar-scanner
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: davidnorton-portfolio
  on:
    repo: piemasters/Portfolio
